**IMPORTING LIBRARIES**

In [1]:
import pandas as pd
import numpy as np

**Loading Dataset**

In [2]:
df = pd.read_csv(r'D:\Projects\Herbalife\AI_Body_Analyzer\dataset\bodyfat.csv')

**Data Overview**

In [3]:
df.shape

(252, 15)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 15 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Density  252 non-null    float64
 1   BodyFat  252 non-null    float64
 2   Age      252 non-null    int64
 3   Weight   252 non-null    float64
 4   Height   252 non-null    float64
 5   Neck     252 non-null    float64
 6   Chest    252 non-null    float64
 7   Abdomen  252 non-null    float64
 8   Hip      252 non-null    float64
 9   Thigh    252 non-null    float64
 10  Knee     252 non-null    float64
 11  Ankle    252 non-null    float64
 12  Biceps   252 non-null    float64
 13  Forearm  252 non-null    float64
 14  Wrist    252 non-null    float64
dtypes: float64(14), int64(1)
memory usage: 29.7 KB

In [5]:
df.head()

,Density,BodyFat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
0,1.0708,12.3,23,154.25,67.75,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1
1,1.0853,6.1,22,173.25,72.25,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2
2,1.0414,25.3,22,154.00,66.25,34.0,95.8,87.9,99.2,59.6,38.9,24.0,28.8,25.2,16.6
3,1.0751,10.4,26,184.75,72.25,37.4,101.8,86.4,101.2,60.1,37.3,22.8,32.4,29.4,18.2
4,1.0340,28.7,24,184.25,71.25,34.4,97.3,100.0,101.9,63.2,42.2,24.0,32.2,27.7,17.7

In [6]:
df.tail()

,Density,BodyFat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
247,1.0736,11.0,70,134.25,67.00,34.9,89.2,83.6,88.8,49.6,34.8,21.5,25.6,25.7,18.5
248,1.0236,33.6,72,201.00,69.75,40.9,108.5,105.0,104.5,59.6,40.8,23.2,35.2,28.6,20.1
249,1.0328,29.3,72,186.75,66.00,38.9,111.1,111.5,101.7,60.3,37.3,21.5,31.3,27.2,18.0
250,1.0399,26.0,72,190.75,70.50,38.9,108.3,101.3,97.8,56.0,41.6,22.7,30.5,29.4,19.8
251,1.0271,31.9,74,207.50,70.00,40.8,112.4,108.5,107.1,59.3,42.2,24.6,33.7,30.0,20.9

I have to convert weight from lbs to kgs 
and height from meter to cms

**Missing Values**

In [7]:
df.isnull().sum()

Density    0
BodyFat    0
Age        0
Weight     0
Height     0
Neck       0
Chest      0
Abdomen    0
Hip        0
Thigh      0
Knee       0
Ankle      0
Biceps     0
Forearm    0
Wrist      0
dtype: int64

**Converting Height and Weight**

In [8]:
df['Weight'] = df['Weight']/2.205
df['Height'] = df['Height'] * 2.54

In [9]:
df.rename(columns={'Weight': 'Weight (cms)' , 'Height': 'Height (cms)'} , inplace = True)

**Dropping Columns**

In [10]:
df = df.drop(columns='Density')

In [11]:
df

,BodyFat,Age,Weight (cms),Height (cms),Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
0,12.3,23,69.954649,172.085,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1
1,6.1,22,78.571429,183.515,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2
2,25.3,22,69.841270,168.275,34.0,95.8,87.9,99.2,59.6,38.9,24.0,28.8,25.2,16.6
3,10.4,26,83.786848,183.515,37.4,101.8,86.4,101.2,60.1,37.3,22.8,32.4,29.4,18.2
4,28.7,24,83.560091,180.975,34.4,97.3,100.0,101.9,63.2,42.2,24.0,32.2,27.7,17.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,11.0,70,60.884354,170.180,34.9,89.2,83.6,88.8,49.6,34.8,21.5,25.6,25.7,18.5
248,33.6,72,91.156463,177.165,40.9,108.5,105.0,104.5,59.6,40.8,23.2,35.2,28.6,20.1
249,29.3,72,84.693878,167.640,38.9,111.1,111.5,101.7,60.3,37.3,21.5,31.3,27.2,18.0
250,26.0,72,86.507937,179.070,38.9,108.3,101.3,97.8,56.0,41.6,22.7,30.5,29.4,19.8
251,31.9,74,94.104308,177.800,40.8,112.4,108.5,107.1,59.3,42.2,24.6,33.7,30.0,20.9

**Numeric Matric Creation**

In [12]:
X = df.drop(columns=["BodyFat" , "Knee" , "Ankle" , "Biceps" , "Forearm" , "Wrist"])
y = df["BodyFat"]

In [13]:
print(X)

     Age  Weight (cms)  Height (cms)  Neck  Chest  Abdomen    Hip  Thigh
0     23     69.954649       172.085  36.2   93.1     85.2   94.5   59.0
1     22     78.571429       183.515  38.5   93.6     83.0   98.7   58.7
2     22     69.841270       168.275  34.0   95.8     87.9   99.2   59.6
3     26     83.786848       183.515  37.4  101.8     86.4  101.2   60.1
4     24     83.560091       180.975  34.4   97.3    100.0  101.9   63.2
..   ...           ...           ...   ...    ...      ...    ...    ...
247   70     60.884354       170.180  34.9   89.2     83.6   88.8   49.6
248   72     91.156463       177.165  40.9  108.5    105.0  104.5   59.6
249   72     84.693878       167.640  38.9  111.1    111.5  101.7   60.3
250   72     86.507937       179.070  38.9  108.3    101.3   97.8   56.0
251   74     94.104308       177.800  40.8  112.4    108.5  107.1   59.3

[252 rows x 8 columns]

In [14]:
print(y)

0      12.3
1       6.1
2      25.3
3      10.4
4      28.7
       ...
247    11.0
248    33.6
249    29.3
250    26.0
251    31.9
Name: BodyFat, Length: 252, dtype: float64

No missing values and no categorical variable so no need to handle this all ....

**Splitting dataset into training and test set**

In [15]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in d:\projects\herbalife\ai_body_analyzer\bodyanalyzer_venv\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in d:\projects\herbalife\ai_body_analyzer\bodyanalyzer_venv\lib\site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in d:\projects\herbalife\ai_body_analyzer\bodyanalyzer_venv\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in d:\projects\herbalife\ai_body_analyzer\bodyanalyzer_venv\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in d:\projects\herbalife\ai_body_analyzer\bodyanalyzer_venv\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y ,test_size= 0.2 , random_state= 1)

**Feature Scaling**

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Training Multiple Regression Model on training data**

In [18]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train , y_train)

LinearRegression()

**Predicting the test set results**

In [19]:
y_pred = regressor.predict(X_test)

**Evaluating Model**

*MAE*

In [20]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test , y_pred)

3.3036807157524124

*R2 Score*

In [21]:
from sklearn.metrics import r2_score
r2_score(y_test , y_pred)

0.7582213988877037

**Training Random Forest Regressor on training data**

In [ ]:
from sklearn.ensemble import RandomForestRegressor
reg = RandomForestRegressor(n_estimators=100 , random_state=0)
reg.fit(X_train , y_train)

RandomForestRegressor(random_state=0)

**Predicting Results**

In [ ]:
y_pred = reg.predict(X_test)

**Evaluating Results**

*MAE*

In [24]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test , y_pred)

4.000549019607845

*r2_score*

In [26]:
from sklearn.metrics import r2_score
r2_score(y_test , y_pred)

0.6931041127244819

linear model performed better than the random forest maybe the size of dataset is small and body fat linealry depends upon abdomen , hips etc ..

**Saving the linear model and scaler**

In [28]:
import joblib 
joblib.dump(regressor, "fat_model.pkl")
joblib.dump(sc, "scaler.pkl")

['scaler.pkl']